language: php
php:
  - 7.1

before_install:
  - apt-get update
  - apt-get install -y nodejs

install:
  - composer install
  - npm install

script:
  - node solid selectEnv staging
  if: branch = master

  - node solid selectEnv staging
  if: branch = staging
  
  - node solid production
  # TODO deployer

