sudo: required
cache:
  - yarn

language: php
php:
  - 7.1

branches:
  only:
    - master
    - staging
    - production

env:
  - NODE_RELEASE=10.x

# Ajouter le domaine au ficher known host de la machine virtuelle
addons:
  ssh_known_hosts: "atelier-medias.org"

# config SSH
before_install:
  # confirm the fingerprint of the unknown server
  #- echo -e "Host atelier-medias.orgntStrictHostKeyChecking non" >> ~/.ssh/config
  #- openssl aes-256-cbc -K ${SSH_ENCRYPTED_PRIVATE_KEY} -iv ${SSH_ENCRYPTED_PRIVATE_KEY} -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  #- eval "$(ssh-agent -s)"
  #- chmod 600 /tmp/deploy_rsa
  #- ssh-add /tmp/deploy_rsa

install:
  # installer node
  - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}"
  - sudo apt-get install -y nodejs
  # aller dans le dossier dist/
  - cd dist/
  # installer les dependances php
  - composer install
  # retourner à la racine
  - cd ..
  # installer des dépendances front
  - yarn install

# selectionner l'environnement de dev en fonction de la branch
before_script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then node solid selectEnv staging; fi
  - if [ "$TRAVIS_BRANCH" == "staging" ]; then node solid selectEnv staging; fi
  - if [ "$TRAVIS_BRANCH" == "production" ]; then node solid selectEnv production; fi

script:
  # builder les sources front
  - node solid production
  # pousser le tout sur le serveur
  # - rsync --checksum -i -r -a -e ssh --delete dist/ ${USER_SERVER}:test/



